# prometheus.yml
global:
  scrape_interval: 1s
scrape_configs:
  - job_name: 'services'
    static_configs:
      - targets: ['localhost:9090', 'qix-engine:9090', 'cadvisor:8080', 'node-exporter:9100']
